### ISSUE TITLE
How to download soundbibe file by the url?

### ISSUE THREAD

**Issue by Darius-H** [XinhaoMei/WavCaps#5]
I found that the url from the soundbibe json file can not be downloaded by wget, how to download this dataset?
```wget -O 0.wav http://soundbible.com/grab.php?id=2219&type=wav``` does not work

**Comment by XinhaoMei** [comment]
Hello,

Could you please try adding quotation marks around the URL link? Like `wget -O 0.wav "http://soundbible.com/grab.php?id=2219&type=wav"`.

**Comment by Darius-H** [comment]
I found that links from free sound can not be downloaded by wget, and only audios less than 2s are provided in google drive. I beg you can provide the crawling script. Thank you very much.

**Comment by XinhaoMei** [comment]
Sorry, I am afiraid I cannot share the script now. You could refer to their website for downloading instructions.

Because crawling these audio clips from FreeSound is not encouraged and we are asked to provided the waveforms by FreeSound. But the whold set is too large (more than 1 TB), we can only provid audio clips less than 2 seconds at this time (already more than 220k audio clips).
